name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            mariadb-version: 10.5
    steps:
    - uses: ankane/setup-mariadb@tmpdir
      with:
        mariadb-version: ${{ matrix.mariadb-version }}
    - run: mysql --version
    - run: mysqladmin create testdb
    - run: mysql -D testdb -e 'SELECT VERSION()'
    - run: ls
